global:
  resolve_timeout: 5m

route:
  receiver: jenkins-rollback-webhook

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://34.201.58.43:8080/generic-webhook-trigger/invoke?token=ROLLBACK_4E13EF_TOKEN'
        send_resolved: false
        http_config:
          basic_auth:
            username: JENKINS_USERNAME_HERE
            password: JENKINS_API_TOKEN_HERE