global:
  resolve_timeout: 5m

route:
  receiver: jenkins-rollback-webhook

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://34.201.58.43:8080/generic-webhook-trigger/invoke?token=ROLLBACK_4E13EF_TOKEN'
        send_resolved: false
        http_config:
          basic_auth:
            username: areebishaq24
            password: 117ffcc0f899fc1ad7b8080e66268f30f5
